{% set version = "3.1.0" %}

package:
  name: threadpoolctl
  version: {{ version }}

source:
  url: https://github.com/joblib/threadpoolctl/archive/{{ version }}.tar.gz
  sha256: 449b806f9147a3cf28ed7ec6389dbff9c450331d695873ab75dea79fe661f1e7

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m flit install

requirements:
  host:
    - python >=3.6
    - flit
  run:
    - python >=3.6

test:
  requires:
    - numpy
  imports:
    - threadpoolctl
  commands:
    - python -m threadpoolctl -i numpy

about:
  home: https://github.com/joblib/threadpoolctl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python helpers to control the threadpools of native libraries

  description: |
    Python helpers to introspect and limit the number of threads used
    in native libraries that handle their own internal threadpool
    (BLAS and OpenMP implementations).
  doc_url: https://github.com/joblib/threadpoolctl
  dev_url: https://github.com/joblib/threadpoolctl

extra:
  recipe-maintainers:
    - ogrisel
    - tomMoral
    - jeremiedbb
